spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog.yaml
  cloud:
    openfeign:
      client:
        config:
          user-service:
            connect-timeout: 3000
            read-timeout: 5000
      circuitbreaker:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.shop.orderservice.model.events"
    listener:
      ack-mode: record
    topics:
      payment-events: payment-events
      payment-events-dlq: payment-events-dlq

user:
  service:
    url: ${USER_SERVICE_URL}

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10

internal:
  service-secret: ${SERVICE_SECRET}
  internal-secret: ${INTERNAL_SECRET}