server:
  port: ${ORDER_SERVICE_PORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
internal:
  service-secret: ${SERVICE_SECRET}
  internal-secret: ${INTERNAL_SECRET}
user:
  service:
    url: ${USER_SERVICE_URL}
gateway:
  url: http://localhost:8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs